import './css/index.css'
import './css/public.css'
import './css/login.css'

// import './js/jquery-1.12.4.min'
// import './js/jquery.flexslider-min'
import 'jquery'
import 'flexslider'
import './js/public'
import './js/nav'
